"""Update model Contact

Revision ID: 43643a8c0281
Revises: 6c55d5f3c7f1
Create Date: 2023-02-26 00:13:05.293488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43643a8c0281'
down_revision = '6c55d5f3c7f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_email_key', 'contacts', type_='unique')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_unique_constraint('contacts_email_key', 'contacts', ['email'])
    # ### end Alembic commands ###
